# my alacritty config :)
# .config/alacritty/alacritty.toml

[window]

opacity = 0.7

[font]

normal.family = "Iosevka Term"
bold.family = "Iosevka Term"
italic.family = "Iosevka Term"
bold_italic.family = "Iosevka Term"

size = 13.0

[colors.primary]

foreground = "#ffffff"
background = "#181818"
